### PR TITLE
Add ROS2 Support (minimal) to work in conjunction with ROS1

### PR DESCRIPTION
**Pull request by vinnnyr**
This adds:
  1. Dockerfile to test building in ROS1 and ROS2
  2. Some unit tests for the `conversor` function, that get built in ROS2
  3.  CMake and Package.xml changes to support ROS1 and ROS2 to live together simultaneously. 
 
I used techniques found in this repo as the pattern for getting ROS1 and ROS2 to live simultaneously. 
https://github.com/luxonis/depthai-ros

Note that the launch / RVIZ functionality is not recreated at the moment.

Maybe it makes sense to have a separate branch to merge this change in (besides `master` ) while we get comfortable with these changes. 

I have tested this builds in ROS1 (via the dockerfile), and tested the build and unit tests for ROS2.

### CODE REVIEW

**Comment by vinnnyr** [comment]
If wanted  I will happily PR `Dockerfile.noetic` separately to `master` so that it can be used by others without being blocked by this PR build.

**Comment by Gonzalo-Mier** [comment]
Hi @vinnnyr,
Really nice PR. Thank you really much for your work. I will create a new branch and we can work there.

**Comment by Gonzalo-Mier** [comment]
We can continue working on the branch [add-ros2-support](https://github.com/Fields2Cover/fields2cover_ros/tree/add-ros2-support)

**Comment by vinnnyr** [comment]
Awesome thanks!  Shall I close this PR then?

**Comment by Gonzalo-Mier** [comment]
I guess we can close it. Thank you again!

**Pull request closed without merging**
